version: 0.2

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"

  build:
    commands:
      - mvn clean package -Dtest=!AgentMonitoringListenerTest,!AsynchronousAgentDispatcherTest,!RunCucumberTest,!*IntegrationTest,!AmazonHttpClientTest,!ClientConfigurationMaxErrorRetryTest,!RetryPolicyAdapterTest,!RetryPolicyTest -DfailIfNoTests=false -T1C
