version: 0.2

phases:

  build:
    commands:
    - mvn clean install -pl :sdk-native-image-test -P quick --am -T1C
    - mvn clean install -pl :bom-internal,:bom
    - cd test/sdk-native-image-test
    - mvn clean package -P native-image
    - target/sdk-native-image-test